field: a5663fba-c59f-43b0-bf33-8df7b7f0a36a # Navigation
fieldLayouts:
  7565caba-5a0b-4f52-9ee7-926c8953c54a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a7a39547-9c0c-4ec7-82fd-63fd5cc45d23 # Icon type
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7732655-ab64-4139-bd2a-cb1a74108411
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4628d87e-22d9-499b-bdf9-18a837b2836b # Icon Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 422c4f88-235e-47af-b3a9-b069b52644df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 135da372-d6b7-43cb-a76d-adcfc216105c
        userCondition: null
fields:
  4628d87e-22d9-499b-bdf9-18a837b2836b: # Icon Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconLink
    instructions: null
    name: 'Icon Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: url
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  a7a39547-9c0c-4ec7-82fd-63fd5cc45d23: # Icon type
    columnSuffix: sqgptjbu
    contentColumnType: string
    fieldGroup: null
    handle: iconType
    instructions: null
    name: 'Icon type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Telephone
            -
              - value
              - telephone
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Mail
            -
              - value
              - mail
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Map
            -
              - value
              - map
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: iconLink
name: 'Icon Link'
sortOrder: 3
