field: a5663fba-c59f-43b0-bf33-8df7b7f0a36a # Navigation
fieldLayouts:
  29f66129-cc09-494b-b047-e79ed5153dd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 393b6ab7-ee65-4ffb-9e54-6f5a1e1a8182 # Network
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1104b4-5433-41cd-bd0b-3c63253750f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3008aa3-4cb5-4a69-a384-56c230019e7b # Link For Network
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fff889d9-1505-44d4-b9e2-9344e1a13633
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3943c01a-c5ae-43d0-b553-ae0623fbc991
        userCondition: null
fields:
  393b6ab7-ee65-4ffb-9e54-6f5a1e1a8182: # Network
    columnSuffix: gkcmgfhy
    contentColumnType: string
    fieldGroup: null
    handle: network
    instructions: null
    name: Network
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - facebook
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - instagram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Linkedin
            -
              - value
              - linkedin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Twitter
            -
              - value
              - twitter
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Github
            -
              - value
              - github
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  e3008aa3-4cb5-4a69-a384-56c230019e7b: # Link For Network
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkForNetwork
    instructions: null
    name: 'Link For Network'
    searchable: false
    settings:
      allowCustomText: false
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: socialNetwork
name: 'Social Network'
sortOrder: 1
