fieldLayouts:
  dbed7a0d-f07e-4cf4-8ae7-e965a6b63a30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 28938e71-eb6a-40aa-b81a-73124e337d91
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11f796f9-b969-4d37-a786-d1d222e62cf7 # Page Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cef1ad25-1760-4e74-b901-de1c400af2d3
            userCondition: null
            warning: null
            width: 100
        name: 'Page Header'
        uid: 80bb82c4-3103-4d7e-bbd0-630fe2646f7a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8663e635-94a3-4915-be8c-33777a7a6dca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63315a2f-7e22-4ac8-bdfe-fcfc728f82d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 651c6f11-7a0d-4318-bb73-ea8c6ab2655a # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b38e9faa-681d-4e8b-b19b-3cf4e3b7811e
            userCondition: null
            warning: null
            width: 100
        name: 'Page Content'
        uid: adb7122b-4ad6-4ff4-afae-21478d361437
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 7fda0ac4-94ee-464a-ae02-595f16739e74 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
