childBlocks: null
conditions: null
description: ''
enabled: true
field: 651c6f11-7a0d-4318-bb73-ea8c6ab2655a # Page Content
fieldLayouts:
  6015b724-7181-4cc1-9da7-7d8be26ddf52:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1b8b8cbc-3d2c-41bc-8ba2-1963284864f9 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec315734-9f70-4cb9-8467-14985d492200
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7706db96-7ecb-4a0d-b973-607acd0101f3 # Redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8ddef5f-4de2-4039-8bc8-996ca28ec72a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: baeb5c2f-3847-4906-ab17-bcad86cc6274 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06c2b35c-2629-4626-8ef9-d92e7819a86d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c25fc587-f118-46e4-9782-59636dda5382
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d02ce07-ac27-4917-ac5c-9d71c8ae60ea # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8547a0ab-4d3e-4316-bd2e-7d4beb09f38a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9debdc48-469d-44b3-97ed-ed1b63afe414 # Margin Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2b3a10c-e5df-472d-a70f-e62a1e1c48ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07ca4a68-c088-41ab-ad3b-ec9eb543d4b7 # Margin Bot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bfe2605-eeea-45ec-bf2d-6cf350a1292f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7e27ca0-f4e5-488a-9f7f-8e9eec5604a4 # Block ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ff8f188-f305-4961-af6d-e33aba0c857d
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 3733e923-9241-438d-997e-085c513bef9f
        userCondition: null
group: c2b558a5-f90d-4fab-b4b7-08dfa050dc27 # Products
groupChildBlockTypes: true
handle: adventureIdea
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Adventure Idea'
sortOrder: 12
topLevel: true
