childBlocks: null
conditions: null
description: ''
enabled: true
field: 651c6f11-7a0d-4318-bb73-ea8c6ab2655a # Page Content
fieldLayouts:
  643bef90-c814-4d4f-a630-d3abf507a719:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Everything will be automatically displayed, or you can select custom entries to show.'
            type: craft\fieldlayoutelements\Tip
            uid: 2bdc3087-e9dc-46ed-875b-7a2946b857a3
            userCondition: null
          -
            elementCondition: null
            fieldUid: 60d0cf0b-c116-4883-acf1-6b7892214209 # Text
            instructions: null
            label: Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88753220-ae2d-4b65-ac2b-279b6cb33baa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61c7b147-937e-4d4e-803f-d38b9d2e3165 # Custom Entries
            instructions: null
            label: 'Custom Ideas'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 472d469a-11b4-4c5a-a0fb-196f4ff4792d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bdfcc55f-2cba-42b0-bcc0-987e190ef639
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d02ce07-ac27-4917-ac5c-9d71c8ae60ea # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e1ab88e-962d-43de-b7b4-def67b0aa166
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9debdc48-469d-44b3-97ed-ed1b63afe414 # Margin Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae321c9c-971c-4bb4-b380-073e15629fec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07ca4a68-c088-41ab-ad3b-ec9eb543d4b7 # Margin Bot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86e7996e-e550-4308-a042-0455ef3e0998
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7e27ca0-f4e5-488a-9f7f-8e9eec5604a4 # Block ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 262707a0-ea88-43db-943c-ebda97e97093
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 5f9ce26f-bd06-4a8e-b68a-488db0120856
        userCondition: null
group: 7a38f408-160a-4f54-9acd-dca1bd383059 # Unique Blocks
groupChildBlockTypes: true
handle: adventureIdeas
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Adventure Ideas'
sortOrder: 4
topLevel: true
