childBlocks: null
conditions: null
description: ''
enabled: true
field: 651c6f11-7a0d-4318-bb73-ea8c6ab2655a # Page Content
fieldLayouts:
  49fce105-1a7c-4f3b-89bf-1ae8b1584bdd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1b8b8cbc-3d2c-41bc-8ba2-1963284864f9 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cf76a45-def3-4822-a1a6-56e5933323cd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 45b21dac-da45-4595-9881-3dc9a2a62260 # Lightswitch
            instructions: null
            label: 'Image on right side?'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 400db1e1-b7f3-439f-9f3b-a9f9cbf8d841
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7706db96-7ecb-4a0d-b973-607acd0101f3 # Redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cefd0aad-554b-4150-879a-68b81a2a3bed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ffab6b83-5f9e-4a37-bc3b-77cc1863e590 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0301546c-e5e3-44a5-ac08-918ac0e34997
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebf6a4d2-cd1b-4581-8b22-bd085fcffe4e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d02ce07-ac27-4917-ac5c-9d71c8ae60ea # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0a0a4b3-1171-481c-9d23-70dda5aa4d09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9debdc48-469d-44b3-97ed-ed1b63afe414 # Margin Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef1e4e1c-5eea-439f-bfdb-64b983c7c761
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07ca4a68-c088-41ab-ad3b-ec9eb543d4b7 # Margin Bot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c10485c1-dd79-4c02-9b77-ffb877bfa8f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7e27ca0-f4e5-488a-9f7f-8e9eec5604a4 # Block ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be0a9174-59de-47d0-9cb5-233f067cee26
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: cf1e925d-af29-4fb6-84a3-fb8f6a26aa5a
        userCondition: null
group: 128d62b5-90de-4899-a2fe-a2cc0fceb24c # Common Blocks
groupChildBlockTypes: true
handle: imageText
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Image Text'
sortOrder: 2
topLevel: true
