childBlocks: null
conditions: null
description: ''
enabled: true
field: 651c6f11-7a0d-4318-bb73-ea8c6ab2655a # Page Content
fieldLayouts:
  0acbd639-07e9-46fc-8380-d3e114663cb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Everything will be automatically displayed.'
            type: craft\fieldlayoutelements\Tip
            uid: e3a64c09-e1db-431c-b12c-36128c944672
            userCondition: null
        name: Content
        uid: 4b7aeb17-8d08-462d-a19f-2de5087f4860
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d02ce07-ac27-4917-ac5c-9d71c8ae60ea # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8ccdfab-47ab-4942-87a4-8021a7f372c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9debdc48-469d-44b3-97ed-ed1b63afe414 # Margin Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15c1b750-d112-4fa0-ba12-9d04a487568d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07ca4a68-c088-41ab-ad3b-ec9eb543d4b7 # Margin Bot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b5a497d-d468-469f-a156-6679a7b90e2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7e27ca0-f4e5-488a-9f7f-8e9eec5604a4 # Block ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d970e449-6e87-4bcb-a0ab-7e58f1d22ba7
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: c365fbd3-6cfb-478a-8e8d-19c89482711c
        userCondition: null
group: 8c22b9c3-be33-42da-a195-63f7c4a1de4c # Forms
groupChildBlockTypes: true
handle: profile
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Profile
sortOrder: 15
topLevel: true
