fieldLayouts:
  81c81f36-ba01-4ab9-8d48-6dff09289c80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ca9eac98-cb1f-46b0-9780-f785ae581781
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87ddb098-2fb3-43fe-ad66-6466a36aef57
        userCondition: null
fs: uploads
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
