columnSuffix: null
contentColumnType: string
fieldGroup: a288c275-3757-471e-82da-49a45b8ef3bc # Common
handle: customComments
instructions: null
name: 'Custom Comments'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 3
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:73a7e511-9235-4e0b-9425-2450143b3b40' # Reviews
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
