columnSuffix: iguriiit
contentColumnType: integer(10)
fieldGroup: a288c275-3757-471e-82da-49a45b8ef3bc # Common
handle: number
instructions: null
name: Number
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
