columnSuffix: null
contentColumnType: string
fieldGroup: a288c275-3757-471e-82da-49a45b8ef3bc # Common
handle: pageContent
instructions: null
name: 'Page Content'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
