changedFieldIndicator: 579570847
field: 11f796f9-b969-4d37-a786-d1d222e62cf7 # Page Header
fieldLayouts:
  055de5f1-b0f9-4218-9bca-74dc5b7b81f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d4a96cf-b1fa-4023-92b9-c4c15cbc6c7c # Background Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b6951ef-8ea8-402b-b5d2-aab4652b3f5d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03bc19d0-35aa-4908-aeba-a0c2fe262438 # Heading Normal
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2f5dddd-937f-4a53-9ab0-2ad4bea0312a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: efeb048d-b9d8-49f0-bc28-de9256f2e2ec # Heading Bold
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33538379-36f9-4f79-b030-411d710eca44
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c9aadfe7-339a-43d8-ad15-5d693b0ee6dd # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc1097bf-c84e-41ea-bc4b-1ce06545b05a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d570024-42e4-41c5-9edb-946cb750c906 # Link button
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f96c2e0d-06cd-40e7-a79a-777cbd1ab8be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b75c71cb-1350-4e32-979c-12b4f84becfe
        userCondition: null
fields:
  0d570024-42e4-41c5-9edb-946cb750c906: # Link button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkButton
    instructions: null
    name: 'Link button'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: category
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  03bc19d0-35aa-4908-aeba-a0c2fe262438: # Heading Normal
    columnSuffix: txuoaaah
    contentColumnType: text
    fieldGroup: null
    handle: headingNormal
    instructions: null
    name: 'Heading Normal'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9d4a96cf-b1fa-4023-92b9-c4c15cbc6c7c: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: null
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:c4247688-c603-4b93-9cee-6d048792716f' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c4247688-c603-4b93-9cee-6d048792716f' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c9aadfe7-339a-43d8-ad15-5d693b0ee6dd: # Text
    columnSuffix: muicahal
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  efeb048d-b9d8-49f0-bc28-de9256f2e2ec: # Heading Bold
    columnSuffix: cjqgmrpx
    contentColumnType: text
    fieldGroup: null
    handle: headingBold
    instructions: null
    name: 'Heading Bold'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
